destination/urls.py
from unicodedata import name
from destination import views
from django.urls import path
from django.urls.conf import include


app_name='destination'


urlpatterns = [
    
    path('',views.destination_list_view,name="destination_list_view"),
    path('<str:slug>',views.destination_detail_view,name="destination_detail_view"),
    path('sites/<str:slug>',views.site_detail_view,name="site_detail_view"),
    path('events/<str:slug>',views.event_detail_view,name="event_detail_view"),
    path('deletecomment/<int:id>',views.delete_comment_view,name="delete_comment_view"),
   

 ]

home/urls.py
from unicodedata import name
from home import views
from django.urls import path

from django.urls.conf import include

"""the app_name variable provided for {% url 'namespace-for-url-ofproject:the nameofviewinpath' and relate it with id%}"""
app_name='home'



urlpatterns = [
    path('',views.home_index,name="home_page_view"),

]

project/urls.py
from unicodedata import name
from django import views
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('admin/',admin.site.urls),
    path('destinations/',include('destination.urls',namespace="destination")),
    path('',include('home.urls',namespace="homepage")),
    path('contact-us/', include('contact.urls',namespace='contact')),
    path('',include('management.urls',namespace="management")),
    
]

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

destination/models.py
from django.db import models

# Create your models here.
from django.utils.text import slugify
from django.contrib.auth.models import User



#this function image_upload for uploading images from image field in Destination model (saving the images with this beginword "destination_img"+instanceid.extension)
def destination_image_upload(instance,filename):
    txt='imgdestination_'
    imagename,extension=filename.split('.')
    return "destinations/%s%s.%s"%(txt,instance.id,extension)

def sites_image_upload(instance,filename):
    txt='imgsites_'
    imagename,extension=filename.split('.')
    return "sites/%s%s.%s"%(txt,instance.id,extension)

def locations_image_upload(instance,filename):
    txt='imglocations_'
    imagename,extension=filename.split('.')
    return "locations/%s%s.%s"%(txt,instance.id,extension)


def events_image_upload(instance,filename):
    txt='imgevents_'
    imagename,extension=filename.split('.')
    return "events/%s%s.%s"%(txt,instance.id,extension)

class Destination(models.Model):
    owner=models.ForeignKey(User,related_name='destination_owner',on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    summary=models.TextField(max_length=1000)
    published_at=models.DateTimeField( auto_now=True)
    image=models.ImageField(upload_to=destination_image_upload)
    slug=models.SlugField(blank=True,null=True)
  
    def save(self,*args,**kwargs):
        self.slug=slugify(self.name)
        super(Destination,self).save(*args, **kwargs)

    def __str__(self) :
        return self.name




class Site(models.Model):
    name=models.CharField(max_length=100)
    summary=models.TextField(max_length=1000)
    image=models.ImageField(upload_to=sites_image_upload)
    location=models.ImageField(upload_to=locations_image_upload)
    destination=models.ForeignKey(Destination, related_name='sites', on_delete=models.CASCADE)
    slug=models.SlugField(blank=True,null=True)
    map_link=models.URLField(max_length=250)



    def save(self,*args,**kwargs):
        self.slug=slugify(self.name)
        super(Site,self).save(*args, **kwargs)

    def __str__(self) :
        return self.name


class Event(models.Model):
    name=models.CharField(max_length=100)
    description=models.TextField(max_length=1000)
    image=models.ImageField(upload_to=events_image_upload)
    price=models.IntegerField(default=0)
    published_at=models.DateTimeField()
    destination=models.ForeignKey(Destination, related_name='events', on_delete=models.CASCADE)
    ticket_link=models.URLField(max_length=250)
    slug=models.SlugField(blank=True,null=True)

    def save(self,*args,**kwargs):
        self.slug=slugify(self.name)
        super(Event,self).save(*args, **kwargs)

    def __str__(self) :
        return self.name

class Comment(models.Model):
    destination = models.ForeignKey(Destination, related_name='comments', on_delete=models.CASCADE)
    username = models.CharField(max_length=25)
    email = models.EmailField()
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User,related_name='comment_owner',on_delete=models.CASCADE)

    class Meta:
        ordering = ['date_added']

destination/forms.py
from django import forms

from .models import Comment





class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

destination/views.py
from django.shortcuts import render,redirect
from .models import Destination,Site,Event,Comment
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import CommentForm
from django.contrib import messages
# Create your views here.

def destination_list_view(request):
    destination_list=Destination.objects.all()
    site_list=Site.objects.all()
    context={'Destinations_list_Var':destination_list,'Sites_list_Var':site_list}
    return render(request,'destinations/destination_list.html',context)


def destination_detail_view(request,slug):
    destination_detail=Destination.objects.get(slug=slug)
    destination_list=Destination.objects.all()
    event_list=Event.objects.all()
    site_list=Site.objects.all()
    if request.method=='POST':
        form=CommentForm(request.POST,request.FILES)
        if form.is_valid():
            myform=form.save(commit=False)
            myform.destination=destination_detail
            myform.username=str(request.user)
            myform.email=str(request.user.email)
            myform.author=request.user
            myform.save()
            return redirect('destination:destination_detail_view',slug=slug)
            form=CommentForm() 
            print('Succesfully Submit')
    else:
        form=CommentForm()

    context={'Destination_detail_Var':destination_detail,'Destinations_list_Var':destination_list,'Sites_list_Var':site_list,'Events_list_Var':event_list,'CommentForm':form}
    return render(request,'destinations/destination_detail.html',context)
    



def site_detail_view(request,slug):
    site_detail=Site.objects.get(slug=slug)
    context={'Site_detail_Var':site_detail}
    return render(request,'destinations/site_detail.html',context)




def event_detail_view(request,slug):
    event_detail=Event.objects.get(slug=slug)
    context={'Event_detail_Var':event_detail}
    return render(request,'destinations/event_detail.html',context)






def delete_comment_view(request,id):
    comment=Comment.objects.get(id=id)
    if request.user==comment.author or request.user.is_superuser:
        comment.delete()
        messages.success(request,("Comment Deleted Successfully!"))
        return redirect('destination:destination_list_view')
         
    else:
        messages.success(request,("You Aren't Authorized To Delete this Comment!!")) 
        return redirect('destination:destination_list_view')

destination/templates/destinations/destination_detail.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}
{% block body %}


<main class="bg-light">
  <section class="bg-dark text-light mt-4  bg-white" 
  style="height: 75vh; min-height: 300px; background-image: url('{{Destination_detail_Var.image.url}}'); background-size: cover; background-position: center; background-repeat: no-repeat;">
    <div class="container h-80 ">
      <div class="row h-100 align-items-center">
        <div class="col-12 text-left ">
          <h1 class="fw-bold text-light"> <i>{{Destination_detail_Var.name}}</i> </h1>
          <p class=" fw-bold text-light ">City in Saudia Arabia</p>
        </div>
      </div>
    </div>
  </section>
  
  <div class="b-example-divider bg-light"></div>

  <section class="p-5 w-100">
    <div class="col-md-12 ">
      <div class="h-100 p-5 border rounded-3 ">
        <h2  class="display-5 fw-bold text-dark">Explore {{Destination_detail_Var.name}} history </h2>
        <p class="lead fw-bold ">{{Destination_detail_Var.summary}}</p>
      </div>
    </div>
  </section>


  



  <div class="b-example-divider bg-light"></div>
<!-- Historical Sites -->
  <section class="p-5">
    <div class="container">
    
      <div class="album py-5 bg-white border rounded-5">
        <div class="container px-4 py-2">
          <h2 class="pb-2 border-bottom">Explore Best Historical sites in {{Destination_detail_Var.name}} City</h2>
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for site in Sites_list_Var %}
          {% if site.destination.name == Destination_detail_Var.name %}
            <div class="col" >
              <a href="{% url 'destination:site_detail_view' site.slug %}" class="text-decoration-none">
                <div class="card shadow-sm ">
                  <img src="{{site.image.url}}" class="card-img-top" width="100%" height="400px" alt="...">
                  <div class="card-body">
  
                    <h5 class="card-title text-dark">{{site.name}}</h5>
                  </div>
                </div>
              </a>
            </div>
          {% endif %}
          {% endfor %}

           
          
          
  
  
          </div>
        </div>
      </div>
    </div>
    
  
  </section>
  


  <div class="b-example-divider bg-light"></div>

  <section class="p-3 w-100 bg-white">
    <div >
      <h2 class="text-center text-dark left-aligned">Events in {{Destination_detail_Var.name}}</h2>
  </div>

  {% for event in Events_list_Var  %}
  {% if event.destination.name == Destination_detail_Var.name %}
  <div class="container col-xxl-8 px-0 py-0 mb-2 bg-light border rounded-5">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
     
      <div class="col-sm-12 col-lg-6">
        <a href="{% url 'destination:event_detail_view' event.slug %}" class="text-decoration-none">
        <img src="{{event.image.url}}"  class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
      </a>
      </div>
    
      <div class="col-lg-6">
        <h1 class="display-6 fw-bold text-dark lh-1 mb-2">{{event.name}}</h1>
       
        <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a href="{% url 'destination:event_detail_view' event.slug %}" class="text-decoration-none">
          <button type="button" class="btn btn-primary btn-lg px-4 me-md-2">Explore</button>
        </a>
           
        </div>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}

</section>


<div class="b-example-divider bg-light"></div>

{% if request.user.is_authenticated  %}

<section class="p-5">
  <div >
    <h2 class="text-center text-dark left-aligned">ADD A comment</h2>
</div>
    <div class="container my-5 py-5">
      <div class="row d-flex justify-content-center">
        <div class="col-md-12 col-lg-10 col-xl-8">
          <div class="card">
            {% for comment in Destination_detail_Var.comments.all %}
            <div class="card-body border-bottom">
              <div class="d-flex flex-start align-items-center">
                <img class="rounded-circle shadow-1-strong me-3"
                src="{% static 'logo/file-person.svg' %}" alt="avatar" width="60"
                  height="60" />
                  
                <div>
                  <h6 class="fw-bold text-primary mb-1">{{ comment.username }}</h6>
                  <p class="text-muted small mb-0">
                    Added At - {{ comment.date_added }}
                  </p>
                </div>
              </div>
  
              <p class="mt-3 mb-4 pb-2">
                {{ comment.body }}.
              </p>
            {% if request.user == comment.author or request.user.is_superuser %}
              <a href="{% url 'destination:delete_comment_view' comment.id %}" class="btn btn-outline-danger btn-sm float-end">Delete</a>
            </div>
            {% endif %}
            {% empty %}
                <div class="text-center">
                    <p>No comments yet!</p>
                </div>
            {% endfor %}

            <div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
              <div class="d-flex flex-start w-100">
                <img class="rounded-circle shadow-1-strong me-3"
                  src="{% static 'logo/file-person.svg' %}" alt="avatar" width="40"
                  height="40" />
                <div class="form-outline w-100">
                  <div class="container">
                    <div class="row my-5">
                        <div class="col-md-12">
                          <form method='POST' enctype="multipart/form-data">
                              {% csrf_token %}
                              
                                  
                                  {% bootstrap_form CommentForm %}
                                  {% buttons %}
                                  <input type="submit" value="Send A Reply" class="boxed-btn3 w-100" />
                                  {% endbuttons %}
                              
                          </form>

                        </div>
                      </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
 
  

</section>

{% endif %}

 <section class="p-5">
  <div class="container">
  
    <div class="album py-5 bg-white border rounded-5">
      <div class="container px-4 py-2">
        <h2 class="pb-2 border-bottom">Explore other cities in Saudi</h2>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for city in Destinations_list_Var %}
        {% if city.name != Destination_detail_Var.name %}
          <div class="col" >
            
            
            <a href='{% url 'destination:destination_detail_view' city.slug %}' class="text-decoration-none">
              <div class="card shadow-sm ">
                <img src="{{city.image.url}}" class="card-img-top" width="100%" height="300px" alt="...">
                <div class="card-body">

                  <h5 class="card-title text-dark">{{city.name}}</h5>
                </div>
              </div>
            </a>
          </div>
          {% endif %}

          {% endfor %}
        
        


        </div>
      </div>
    </div>
  </div>
  

</section> 


</main>

<div class="b-example-divider bg-light"></div>
<!-- Hereeeeeeeeeeeeee -->




{% endblock body %}
 
  

  

  
  

destination/templates/destinations/destination_list.html
{% extends 'base.html' %}
{% load static  %}


  <!-- Showcase -->

  {% block body %}
  

  
  <section class="bg-dark text-light mt-4">
    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="3" aria-label="Slide 4"></button>
      </div>
      <div class="carousel-inner ">
        <div class="carousel-item active">
           
          <img src="{% static 'img/Carsouel_saudiV2.jpg' %}" class="d-block w-100 h-100" alt="...">
  
        </div>
        <div class="carousel-item">
          <img src="{% static 'img/Carsouel_Saudiv4.jpg' %}" class="d-block w-100 h-100" alt="...">
  
        </div>
        <div class="carousel-item">
          <img src="{% static 'img/Carsouel_Saudiv3.jpg' %}" class="d-block w-100 h-100" alt="...">
  
        </div>
        <div class="carousel-item">
          <img src="{% static 'img/homepage_beach-in-saudi-arabia.jpg' %}" class="d-block w-100 h-100" alt="...">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  
      
    
  </section>



  <!-- Boxes -->
  <section class="p-5">
    <div class="container">
        <h2 class="text-center text-dark">Discover Saudia Arabia Tourism</h2>
        <p class="lead text-center text-dark mb-5">
          Saudi Arabia is widely seen as the final frontier of tourism. As the birthplace of Islam, and a millennia-old crossroads of pilgrims and traders, the Kingdom’s rich culture and diverse heritage has no equal. In September 2019, Saudi Arabia opened its doors to the world for the first time. The launch of the Kingdom’s tourism visa saw visitors from around the globe flock to explore Saudi’s ancient history, striking landscapes, and warm hospitality. Last year, Saudi Arabia welcomed 67 million visitors, a sure sign that Vision 2030 is shaping the future of the Kingdom’s travel and tourism sector. 
        </p>
    
      <div class="album py-5 bg-white">
        <div class="container">
    
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
           {% for destination in Destinations_list_Var  %}
            <div class="col" >
              

              <div class="card shadow-sm ">
                <a href="{% url 'destination:destination_detail_view' destination.slug %}" class="text-decoration-none">
                <img src="{{destination.image.url}}" class="card-img-top" width="100%" height="225" alt="...">
                </a>
                <div class="card-body">
                  <h5 class="fw-bold text-dark card-title">{{destination.name}}</h5>
                  
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <a href="{% url 'destination:destination_detail_view' destination.slug %}" class="text-decoration-none">
                      <button type="button" class="btn btn-sm btn-outline-secondary"> View</button>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    
  </div>
  </section>

 
  <section id="tourism" class="p-5 bg-light">
    <div class="container">
      <div class="row align-items-center justify-content-between">
        <div class="col-md">
          <img src="{% static 'img/saud.jpg' %}" class="img-fluid" alt="" />
        </div>
        <div class="col-md p-5">
          <h2>Tourism in Saudi Arabia</h2>
          <p class="lead">
            Tourism development is an important driver of growth for the future of Saudi Arabia. It is one of the key pillars at the heart of Vision 2030’s plan to help diversify the economy and reduce reliance on oil. The Ministry of Tourism, the Saudi Tourism Authority and the Tourism Development Fund were established in line with international best practice and with clear remits to support the growth of this significant sector and help it to flourish.
          </p>
          
  
        </div>
      </div>
    </div>
  </section>




  <section id="Tours" class="p-5" >
    <div class="container">
      <div>
        <h2 class="text-center text-dark">Top Best Sites to Visit In Saudia Arabia</h2>
      </div>
      
      
      
      <p class="lead text-center text-dark mb-5">
        Our Best Historical Sites 
        
      </p>
      
      <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for site in Sites_list_Var|slice:":4"  %}
        
        <div class="col ">
          <div class="card">
            <a href="{% url 'destination:site_detail_view' site.slug %}" class="text-decoration-none">
            <img src="{{site.image.url}}" class="card-img-top"  width="100%" height="300" alt="...">
            </a>
            <p class=" lead card-text">Place in {{site.destination}}</p>
            <div class="card-body">
              <h5 class="card-title text-dark">{{site.name}}</h5>
              
            </div>
          </div>
       
        </div>
    
        {% endfor %}
      </div>
    </div>
  </section>
  <div class="b-example-divider bg-light"></div>
 
  

  
  {% endblock body %}
  
  
    

destination/templates/destinations/event_detail.html
{% extends 'base.html' %}


  

  {% block body %}

<main class="bg-light">
  <section class="bg-dark text-light mt-4  bg-white" style="height: 75vh; min-height: 300px; background-image: url('{{Event_detail_Var.image.url}}'); background-size: cover; background-position: center; background-repeat: no-repeat;">
    <div class="container h-100 ">
      <div class="row h-100 align-items-center">
        <div class="col-12 text-left ">
          <h1 class="fw-bold text-light"> <i>{{Event_detail_Var.name}}</i> </h1>
          <p class=" fw-bold text-light ">An Event Happened {{Event_detail_Var.destination.name}} </p>
        </div>
      </div>
    </div>
  </section>
  
 
    <div class="col-md-12 ">
      <div class="h-100 p-5 border rounded-3 ">
        <h2  class="display-5 fw-bold text-dark"> {{Event_detail_Var.name}} </h2>
        <p class="lead fw-bold ">{{Event_detail_Var.description}}.</p>
      </div>
    </div>
  </section>



  <section class="p-5 w-100">
    <div class="container p-5">
      <div class="row">
        
        <div class="col-lg-12 col-md-12 mb-4 text-center">
          <div class="card h-100 shadow-lg">
            <div class="card-body">
              <div class="text-center p-3">
                <h5 class="card-title">{{Event_detail_Var.name}}</h5>
                <small>Happened At {{Event_detail_Var.published_at}} </small>
                <br><br>
                <span class="h2">Only SR {{Event_detail_Var.price}}</span> 
                <br><br>
                <p class="lead fw-bold">Have Your Ticket Now !</p>
                <br><br>

              </div>
            </div>
         


            <div class="card-body text-center">
              <a href="{{Event_detail_Var.ticket_link}}" class="text-decoration-none">
              <button class="btn btn-outline-primary btn-lg" style="border-radius:30px">Pay</button>
            </a>
            </div>
          </div>
        </div>

      </div>    
    </div>
  </section>


</main>

<div class="b-example-divider bg-light"></div>





  

<!-- Hereeeeeeeeeeeeee -->



{% endblock body %}


 
  

  

  
  

destination/templates/destinations/site_detail.html
{% extends 'base.html' %}
{% block body %}

<main class="bg-light">
  <section class="bg-dark text-light mt-4  bg-white" 
  style="height: 75vh; min-height: 100px; background-image: url('{{Site_detail_Var.image.url}}'); background-size: cover; background-position: center; background-repeat: no-repeat;">
    <div class="container h-100 ">
      <div class="row h-100 align-items-center">
        <div class="col-12 text-left ">
          <h1 class="fw-bold text-light"> <i>{{Site_detail_Var.name}}</i> </h1>
          <p class=" fw-bold text-light ">Site in {{Site_detail_Var.destination.name}} </p>
        </div>
      </div>
    </div>
  </section>
  

  <section class="p-5 w-100">
    <div class="col-md-12 ">
      <div class="h-100 p-5 border rounded-3 ">
        <h2  class="display-5 fw-bold text-dark">Explore {{Site_detail_Var.name}}  </h2>
        <p class="lead fw-bold ">{{Site_detail_Var.summary}}.</p>
      </div>
    </div>
  </section>


  <div class="b-example-divider bg-light"></div>
  <div class="container">
    <div class="row my-2">
        <div class="col-lg-12 text-left ">
          <h1 class="fw-bold text-dark"> <i>To Visit The Location</i> </h1>
          <br>
            <a href="{{Site_detail_Var.map_link}}" class="btn btn-outline-secondary btn-lg m-0  ">Click here</a>
          
        </div>
      </div>
    </div>
<!-- Historical Sites -->
  <section class="p-5">
    <div class="container">
    
      <div class="album py-5 bg-white border rounded-5">
        <div class="container px-4 py-2">
          <h2 class="pb-2 border-bottom text-center"></h2>
          <div class="col-lg-12 col-md-12 mb-4 text-center">
         

            <div class="col align-items-center justify-content-center" >
              
                <div class="card shadow-sm  ">
                  <img src="{{Site_detail_Var.location.url}}" class="card-img-top" width="100%" height="400px" alt="...">
                </div>
           
            </div>
           
          
          
  
  
          </div>
        </div>
      </div>
    </div>
    
  
  </section>
  








</main>

<!-- Hereeeeeeeeeeeeee -->





<div class="b-example-divider bg-light"></div>
 
  

{% endblock %}

  
  