accounts/urls.py
from accounts import views
from django.urls import path

from django.urls.conf import include

"""the app_name variable provided for {% url 'namespace-for-url-ofproject:the nameofviewinpath' and relate it with id%}"""
app_name='accounts'


urlpatterns = [
    path('register',views.register,name="register"),
    path('profile',views.profile,name="profile"),
    path('profile/edit',views.profile_edit,name="profile_edit"),
    
]

home/urls.py
from unicodedata import name
from home import views
from django.urls import path

from django.urls.conf import include

"""the app_name variable provided for {% url 'namespace-for-url-ofproject:the nameofviewinpath' and relate it with id%}"""
app_name='home'



urlpatterns = [
    path('',views.home_index,name="home_page_view"),

]

project/urls.py
from unicodedata import name
from django import views
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('admin/',admin.site.urls),
    path('destinations/',include('destination.urls',namespace="destination")),
    path('',include('home.urls',namespace="homepage")),
    path('contact-us/', include('contact.urls',namespace='contact')),
    path('',include('management.urls',namespace="management")),
    
]

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.
def profile_image_upload(instance,filename):
    txt='imgprofile_'
    imagename,extension=filename.split('.')
    return "profiles/%s%s.%s"%(txt,instance.id,extension)

class Profile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number=models.CharField(max_length=15)
    image=models.ImageField(upload_to=profile_image_upload)

    def __str__(self):
        return str(self.user)


#SIGNAL IS HAPPEN AFTER WE POST_SAVE THAT'S MEAN AFTER SAVING ANEW USER WE WILL HAVE A NEW PROFILE

@receiver(post_save,sender=User)
def create_user_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import fields

from accounts.models import Profile


class SignupForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2']

class UserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','first_name','last_name','email']



class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=['phone_number','image']

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from .forms import SignupForm,ProfileForm,UserForm
from .models import Profile
from django.urls import reverse
# Create your views here.

def register(request):
    if request.method=='POST':
        form=SignupForm(request.POST)
        if form.is_valid:
            form.save()
            #send username and password to authenticate and login to profile after signup
            username=form.cleaned_data['username']
            password=form.cleaned_data['password1']
            user=authenticate(username=username,password=password)
            login(request,user)
            return redirect('/accounts/profile')

            
    else:
        form=SignupForm()

    return render(request,'registration/signup.html',{'signupform':form})


def profile(request):
    profile = Profile.objects.get(user=request.user)
    return render(request,'accounts/profile.html',{'profile': profile})


def profile_edit(request):
    profile = Profile.objects.get(user=request.user)

    if request.method=='POST':
        user_form=UserForm(request.POST,instance=request.user)
        profile_form=ProfileForm(request.POST,request.FILES,instance=profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            myprofile_form=profile_form.save(commit=False)
            myprofile_form.user = request.user
            myprofile_form.save()

            return redirect(reverse('accounts:profile'))

    else:
        user_form=UserForm(instance=request.user)
        profile_form=ProfileForm(instance=profile)



    return render(request,'accounts/profile_edit.html',{"User_Form":user_form,"Profile_Form":profile_form})

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row my-5">
        <div class="col-md-12">
            <div>
                <div>
                    <h3>Profile Summery</h3>
                </div>
                <div>
                    <ul>
                        <li> Name: <span>{{profile}}</span></li>
                        <li>Email: <span>{{profile.user.email}}</span></li>
                        <li>Phone: <span>{{profile.phone_number}}</span></li>
                        <!--<li>Imge <span>{{profile.imge}}</span></li>-->
                        
                    </ul>
                    
                </div>
                <div class="p-5">
                    <a class="boxed-btn3 w-100" href="{% url 'accounts:profile_edit' %}">Edit Profile</a>

                </div>

            </div>


        </div>
    </div>
</div>

    {% endblock body %}

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}

<div class="container">
    <div class="row my-5">
        <div class="col-md-12">
            <h4>Edit Your Profile</h4>
            <form method='POST' enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form User_Form %}
                {% bootstrap_form Profile_Form %}
                
                {% buttons %}
                    <button class="boxed-btn3 w-100" type="submit">Save Changes</button>
                {% endbuttons %}

                    
            </form>
        </div>
    </div>
</div>

{% endblock body %}