home/urls.py
from unicodedata import name
from home import views
from django.urls import path

from django.urls.conf import include

"""the app_name variable provided for {% url 'namespace-for-url-ofproject:the nameofviewinpath' and relate it with id%}"""
app_name='home'



urlpatterns = [
    path('',views.home_index,name="home_page_view"),

]

management/urls.py
from unicodedata import name
from management import views
from django.urls import path

from django.urls.conf import include

"""the app_name variable provided for {% url 'namespace-for-url-ofproject:the nameofviewinpath' and relate it with id%}"""
app_name='management'



urlpatterns = [
    ########Destination path##########
    path('destinatons-list',views.destlist_view,name="destlist_view"),
    path('show-destinaton/<str:slug>',views.showdest_view,name="showdest_view"),
    path('update-destinaton/<str:slug>',views.updatedest_view,name="updatedest_view"),
    path('create-destinaton',views.createdest_view,name="createdest_view"),
    path('delete-destinaton/<str:slug>',views.deletedest_view,name="deletedest_view"),

    ########Site path##########
    path('sites-list',views.sitelist_view,name="sitelist_view"),
    path('show-site/<str:slug>',views.showsite_view,name="showsite_view"),
    path('update-site/<str:slug>',views.updatesite_view,name="updatesite_view"),
    path('create-site',views.createsite_view,name="createsite_view"),
    path('delete-site/<str:slug>',views.deletesite_view,name="deletesite_view"),

    ########Event path ########
    path('events-list',views.eventlist_view,name="eventlist_view"),
    path('show-event/<str:slug>',views.showevent_view,name="showevent_view"),
    path('update-event/<str:slug>',views.updateevent_view,name="updateevent_view"),
    path('create-event',views.createevent_view,name="createevent_view"),
    path('delete-event/<str:slug>',views.deleteevent_view,name="deleteevent_view"),

]

project/urls.py
from unicodedata import name
from django import views
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('admin/',admin.site.urls),
    path('destinations/',include('destination.urls',namespace="destination")),
    path('',include('home.urls',namespace="homepage")),
    path('contact-us/', include('contact.urls',namespace='contact')),
    path('',include('management.urls',namespace="management")),
    
]

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

management/models.py
from django.db import models

# Create your models here.

management/forms.py
from django import forms

from destination.models import Destination,Event,Site









class DestinationForm(forms.ModelForm):
    class Meta:
        model = Destination
        fields="__all__"
        exclude=('slug','owner')





class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields="__all__"
        exclude=('slug',)
  


class SiteForm(forms.ModelForm):
    class Meta:
        model = Site
        fields="__all__"
        exclude=('slug',)
  

management/views.py
from django.http import HttpResponse
from django.shortcuts import render
from destination.models import *
from .forms import EventForm,DestinationForm,SiteForm
from django.shortcuts import render,redirect
from django.contrib import messages
from django.urls import reverse

# Create your views here.


#Start of Destination-Views-Fucntions Section

def destlist_view(request):
    if request.user.is_superuser:
        dest_list=Destination.objects.all()
        context={"All_Destinations_Var":dest_list}
        return render(request,'management/dest_list.html',context)
    else:
        return HttpResponse("<h1>You are Not Authorized To Access Here</h1>")




def showdest_view(request,slug):
    if request.user.is_superuser:
        dest_show=Destination.objects.get(slug=slug)
        context={"Destination_Var":dest_show}
        return render(request,'management/dest_show.html',context)
    else:
        return HttpResponse("<h1>You are Not Authorized To Access Here</h1>")



def createdest_view(request):
    if request.user.is_superuser:
        if request.method=="POST":
            form=DestinationForm(request.POST,request.FILES)
            if form.is_valid():
                myform=form.save(commit=False)
                myform.owner=request.user
                myform.save()
                form=DestinationForm() #this line is for clear all form fields after submitting
                return redirect(reverse('management:destlist_view'))
        else:
            form=DestinationForm()
        return render(request,'management/dest_create.html',{'dest_form':form})
    else:
        return HttpResponse("<h1>You are Not Authorized To Access Here</h1>")


def updatedest_view(request,slug):
    if request.user.is_superuser:
        dest=Destination.objects.get(slug=slug)
        if request.method=="POST":
            form=DestinationForm(request.POST,request.FILES,instance=dest)
            if form.is_valid():
                myform=form.save(commit=False)
                myform.owner=request.user
                myform.save()
                form=DestinationForm() #this line is for clear all form fields after submitting
                return redirect(reverse('management:destlist_view'))
        else:
            form=DestinationForm(instance=dest)

        return render(request,'management/dest_update.html',{"updatedest_form":form,"Destination_Var":dest})
    else:
        return HttpResponse("<h1>You are Not Authorized To Access Here</h1>")


def deletedest_view(request,slug):
    if request.user.is_superuser:
        dest=Destination.objects.get(slug=slug)
        dest.delete()
        messages.success(request,("Destination Deleted Successfully!"))
        return redirect(reverse('management:destlist_view'))
    else:
        return HttpResponse("<h1>You are Not Authorized To Access Here</h1>")
    

#END Of Destination-Views-Fucntions Section

##################################


# Start of Site-Views-Fucntions Section



def sitelist_view(request):
    if request.user.is_superuser:
        site_list=Site.objects.all()
        context={"All_Sites_Var":site_list}
        return render(request,'management/site_list.html',context)




def showsite_view(request,slug):
    if request.user.is_superuser:
        site_show=Site.objects.get(slug=slug)
        context={"Site_Var":site_show}
        return render(request,'management/site_show.html',context)
    else:
        return HttpResponse("<h1>You are Not Authorized To Access Here</h1>")


def createsite_view(request):
    if request.user.is_superuser:
        if request.method=="POST":
            form=SiteForm(request.POST,request.FILES)
            if form.is_valid():
                form.save()
                form=SiteForm() #this line is for clear all form fields after submitting
                return redirect(reverse('management:sitelist_view'))
        else:
            form=SiteForm()
        return render(request,'management/site_create.html',{'site_form':form})
    else:
        return HttpResponse("<h1>You are Not Authorized To Access Here</h1>")


def updatesite_view(request,slug):
    if request.user.is_superuser:
        site=Site.objects.get(slug=slug)
        if request.method=="POST":
            form=SiteForm(request.POST,request.FILES,instance=site)
            if form.is_valid():
                form.save()
                form=SiteForm() #this line is for clear all form fields after submitting
                return redirect(reverse('management:sitelist_view'))
        else:
            form=SiteForm(instance=site)

        return render(request,'management/site_update.html',{"updatesite_form":form,"Site_Var":site})
    else:
        return HttpResponse("<h1>You are Not Authorized To Access Here</h1>")
  

def deletesite_view(request,slug):
    if request.user.is_superuser:
        site=Site.objects.get(slug=slug)
        site.delete()
        messages.success(request,("Site Deleted Successfully!"))
        return redirect(reverse('management:sitelist_view'))
    else:
        return HttpResponse("<h1>You are Not Authorized To Access Here</h1>")    


#END Of Site-Views-Fucntions Section



####################################################################




# Start of Event-Views-Fucntions Section



def eventlist_view(request):
    if request.user.is_superuser:
        event_list=Event.objects.all()
        context={"All_Events_Var":event_list}
        return render(request,'management/event_list.html',context)
    else:
        return HttpResponse("<h1>You are Not Authorized To Access Here</h1>")



def showevent_view(request,slug):
    if request.user.is_superuser:
        event_show=Event.objects.get(slug=slug)
        context={"Event_Var":event_show}
        return render(request,'management/event_show.html',context)
    else:
        return HttpResponse("<h1>You are Not Authorized To Access Here</h1>")


def createevent_view(request):
    if request.user.is_superuser:
        if request.method=="POST":
            form=EventForm(request.POST,request.FILES)
            if form.is_valid():
                form.save()
                form=EventForm() #this line is for clear all form fields after submitting
                return redirect(reverse('management:eventlist_view'))
        else:
            form=EventForm()
        return render(request,'management/event_create.html',{'event_form':form})
    else:
        return HttpResponse("<h1>You are Not Authorized To Access Here</h1>")


def updateevent_view(request,slug):
    if request.user.is_superuser:
        event=Event.objects.get(slug=slug)
        if request.method=="POST":
            form=EventForm(request.POST,request.FILES,instance=event)
            if form.is_valid():
                form.save()
                form=EventForm() #this line is for clear all form fields after submitting
                return redirect(reverse('management:eventlist_view'))
        else:
            form=EventForm(instance=event)

        return render(request,'management/event_update.html',{"updateevent_form":form,"Event_Var":event})
    else:
        return HttpResponse("<h1>You are Not Authorized To Access Here</h1>")


def deleteevent_view(request,slug):
    if request.user.is_superuser:
        event=Event.objects.get(slug=slug)
        event.delete()
        messages.success(request,("Event Deleted Successfully!"))
        return redirect(reverse('management:eventlist_view'))
    else:
        return HttpResponse("<h1>You are Not Authorized To Access Here</h1>")       


#END Of Event-Views-Fucntions Section

management/templates/management/dest_create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}

<div class="container">
    <div class="row my-5">
        <div class="col-md-12">
            <h4>Create New Destination</h4>
            <form method='POST' enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form dest_form %}
                
                {% buttons %}
                    <button class="boxed-btn3 w-100" type="submit">Create</button>
                {% endbuttons %}

                    
            </form>
        </div>
    </div>
</div>

{% endblock body %}

management/templates/management/dest_list.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}

<div class="container">
    <div class="row my-5">
        <div class="col-md-12">
            <h4>ALL Destinations</h4>
            <a href="{% url 'management:createdest_view' %}" class="btn btn-indigo btn-primary btn-sm m-0 float-end">Create</a>
            <table class="table table-striped table-responsive-md  btn-table">

                <thead>
                  <tr>
                    <th>#</th>
                    <th>Destination Name</th>
                    
                    <th></th>
                    <th></th
                    
                  </tr>
                </thead>
                
                <tbody>
                {% for destination in All_Destinations_Var %}
                  <tr>
                    <th scope="row"></th>
                    <td><a href="{% url 'management:showdest_view' destination.slug %}">{{destination.name}}</a></td>
                    <td>
                        <a href="{% url 'management:updatedest_view' destination.slug %}" class="btn btn-indigo btn-warning btn-sm m-0">Update</a>
                    </td>
                    <td>
                        <a href="{% url 'management:deletedest_view' destination.slug %}" class="btn btn-indigo btn-danger btn-sm m-0">Delete</a>
                    </td>
                    
                  </tr>
                  {% endfor %} 
                </tbody>
                
                </table>
        </div>
    </div>
</div>

{% endblock body %}

management/templates/management/dest_show.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}
{% block body %}

<div class="b-example-divider bg-light"></div>
<main class="bg-light">
  <section class="bg-dark text-light mt-4  bg-white" 
  style="height: 75vh; min-height: 300px; background-image: url('{{Destination_Var.image.url}}'); background-size: cover; background-position: center; background-repeat: no-repeat;">
    <div class="container h-100 ">
      <div class="row h-100 align-items-center">
        <div class="col-12 text-left ">
          <h1 class="fw-bold text-light"> <i>{{Destination_Var.name}}</i> </h1>
          <p class=" fw-bold text-light">City in Saudia Arabia</p>
        </div>
      </div>
    </div>
  </section>
  
  <div class="b-example-divider bg-light"></div>

  <section class="p-5 w-100">
    <div class="col-md-12 ">
      <div class="h-100 p-5 border rounded-3 ">
        <h2  class="display-5 fw-bold text-dark">Explore {{Destination_Var.name}} history </h2>
        <p class="lead fw-bold ">{{Destination_Var.summary}}</p>
      </div>
    </div>
  </section>

</main>

<div class="b-example-divider bg-light"></div>
{% endblock %}

management/templates/management/dest_update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}

<div class="container">
    <div class="row my-5">
        <div class="col-md-12">
            <h4>Update Your Destination</h4>
            <form method='POST' enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form updatedest_form %}
                
                {% buttons %}
                    <button class="boxed-btn3 w-100" type="submit">Create</button>
                {% endbuttons %}

                    
            </form>
        </div>
    </div>
</div>

{% endblock body %}

management/templates/management/event_create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}

<div class="container">
    <div class="row my-5">
        <div class="col-md-12">
            <h4>Create New Event</h4>
            <a href="{% url 'management:createevent_view' %}" class="btn btn-indigo btn-primary btn-sm m-0 float-end">Create</a>
            <form method='POST' enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form event_form %}
                
                {% buttons %}
                    <button class="boxed-btn3 w-100" type="submit">Create</button>
                {% endbuttons %}

                    
            </form>
        </div>
    </div>
</div>

{% endblock body %}

management/templates/management/event_list.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}

<div class="container">
    <div class="row my-5">
        <div class="col-md-12">
            <h4>ALL Events</h4>
            <a href="{% url 'management:createevent_view' %}" class="btn btn-indigo btn-primary btn-sm m-0 float-end">Create</a>

            <table class="table table-striped table-responsive-md  btn-table">

                <thead>
                  <tr>
                    <th>#</th>
                    <th>Event Name</th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>
                
                <tbody>
                {% for event in All_Events_Var %}
                  <tr>
                    <th scope="row"></th>
                    <td><a href="{% url 'management:showevent_view' event.slug %}">{{event.name}}</a></td>
                    <td>
                        <a href="{% url 'management:updateevent_view' event.slug %}" class="btn btn-indigo btn-warning btn-sm m-0">Update</a>
                    </td>
                    <td>
                        <a href="{% url 'management:deleteevent_view' event.slug %}" class="btn btn-indigo btn-danger btn-sm m-0">Delete</a>
                    </td>
                    
                  </tr>
                  {% endfor %} 
                </tbody>
                
                </table>
        </div>
    </div>
</div>

{% endblock body %}

management/templates/management/event_show.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}
{% block body %}

<div class="b-example-divider bg-light"></div>
<main class="bg-light">
  <section class="bg-dark text-light mt-4  bg-white" 
  style="height: 75vh; min-height: 300px; background-image: url('{{Event_Var.image.url}}'); background-size: cover; background-position: center; background-repeat: no-repeat;">
    <div class="container h-100 ">
      <div class="row h-100 align-items-center">
        <div class="col-12 text-left ">
          <h1 class="fw-bold text-light"> <i>{{Event_Var.name}}</i> </h1>
          <p class=" fw-bold text-light">Event in {{Event_Var.destination.name}} </p>
        </div>
      </div>
    </div>
  </section>
  
  <div class="b-example-divider bg-light"></div>

  <section class="p-5 w-100">
    <div class="col-md-12 ">
      <div class="h-100 p-5 border rounded-3 ">
        <h2  class="display-5 fw-bold text-dark">Explore {{Event_Var.name}} history </h2>
        <p class="lead fw-bold ">{{Event_Var.description}}</p>
      </div>
    </div>
  </section>

</main>

<div class="b-example-divider bg-light"></div>
{% endblock %}

management/templates/management/event_update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}

<div class="container">
    <div class="row my-5">
        <div class="col-md-12">
            <h4>Update Your Event</h4>
            <form method='POST' enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form updateevent_form %}
                
                {% buttons %}
                    <button class="boxed-btn3 w-100" type="submit">Update</button>
                {% endbuttons %}

                    
            </form>
        </div>
    </div>
</div>

{% endblock body %}

management/templates/management/site_create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}

<div class="container">
    <div class="row my-5">
        <div class="col-md-12">
            <h4>Create New Site</h4>
            <form method='POST' enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form site_form %}
                
                {% buttons %}
                    <button class="boxed-btn3 w-100" type="submit">Create</button>
                {% endbuttons %}

                    
            </form>
        </div>
    </div>
</div>

{% endblock body %}

management/templates/management/site_list.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}

<div class="container">
    <div class="row my-5">
        <div class="col-md-12">
            <h4>ALL Sites</h4>
            <a href="{% url 'management:createsite_view' %}" class="btn btn-indigo btn-primary btn-sm m-0 float-end">Create</a>
            <table class="table table-striped table-responsive-md  btn-table">

                <thead>
                  <tr>
                    <th>#</th>
                    <th>Site Name</th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>
                
                <tbody>
                {% for site in All_Sites_Var %}
                  <tr>
                    <th scope="row"></th>
                    
                    <td><a href="{% url 'management:showsite_view' site.slug %}">{{site.name}}</a></td>
                    <td>
                        <a href="{% url 'management:updatesite_view' site.slug %}" class="btn btn-indigo btn-warning btn-sm m-0">Update</a>
                    </td>
                    <td>
                        <a href="{% url 'management:deletesite_view' site.slug %}" class="btn btn-indigo btn-danger btn-sm m-0">Delete</a>
                    </td>
                    
                  </tr>
                  {% endfor %} 
                </tbody>
                
                </table>
        </div>
    </div>
</div>

{% endblock body %}

management/templates/management/site_show.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}
{% block body %}

<div class="b-example-divider bg-light"></div>
<main class="bg-light">
  <section class="bg-dark text-light mt-4  bg-white" 
  style="height: 75vh; min-height: 300px; background-image: url('{{Site_Var.image.url}}'); background-size: cover; background-position: center; background-repeat: no-repeat;">
    <div class="container h-100 ">
      <div class="row h-100 align-items-center">
        <div class="col-12 text-left ">
          <h1 class="fw-bold text-light"> <i>{{Site_Var.name}}</i> </h1>
          <p class=" fw-bold text-light">Site in {{Site_Var.destination.name}}</p>
        </div>
      </div>
    </div>
  </section>
  
  <div class="b-example-divider bg-light"></div>

  <section class="p-5 w-100">
    <div class="col-md-12 ">
      <div class="h-100 p-5 border rounded-3 ">
        <h2  class="display-5 fw-bold text-dark">Explore {{Site_Var.name}} history </h2>
        <p class="lead fw-bold ">{{Site_Var.summary}}</p>
      </div>
    </div>
  </section>

</main>

<div class="b-example-divider bg-light"></div>
{% endblock %}

management/templates/management/site_update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}

<div class="container">
    <div class="row my-5">
        <div class="col-md-12">
            <h4>Update Your Site</h4>
            <form method='POST' enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form updatesite_form %}
                
                {% buttons %}
                    <button class="boxed-btn3 w-100" type="submit">Update</button>
                {% endbuttons %}

                    
            </form>
        </div>
    </div>
</div>

{% endblock body %}