accounts/urls.py
from accounts import views
from django.urls import path

from django.urls.conf import include

"""the app_name variable provided for {% url 'namespace-for-url-ofproject:the nameofviewinpath' and relate it with id%}"""
app_name='accounts'


urlpatterns = [
    path('register',views.register,name="register"),
    path('profile',views.profile,name="profile"),
    path('profile/edit',views.profile_edit,name="profile_edit"),
    
]

contact/urls.py
from django.urls import include, path

from . import views

app_name='contact'

urlpatterns = [
    path('',views.send_message , name='contact_view'),
]

destination/urls.py
from unicodedata import name
from destination import views
from django.urls import path
from django.urls.conf import include


app_name='destination'


urlpatterns = [
    
    path('',views.destination_list_view,name="destination_list_view"),
    path('<str:slug>',views.destination_detail_view,name="destination_detail_view"),
    path('sites/<str:slug>',views.site_detail_view,name="site_detail_view"),
    path('events/<str:slug>',views.event_detail_view,name="event_detail_view"),
    path('deletecomment/<int:id>',views.delete_comment_view,name="delete_comment_view"),
   

 ]

home/urls.py
from unicodedata import name
from home import views
from django.urls import path

from django.urls.conf import include

"""the app_name variable provided for {% url 'namespace-for-url-ofproject:the nameofviewinpath' and relate it with id%}"""
app_name='home'



urlpatterns = [
    path('',views.home_index,name="home_page_view"),

]

management/urls.py
from unicodedata import name
from management import views
from django.urls import path

from django.urls.conf import include

"""the app_name variable provided for {% url 'namespace-for-url-ofproject:the nameofviewinpath' and relate it with id%}"""
app_name='management'



urlpatterns = [
    ########Destination path##########
    path('destinatons-list',views.destlist_view,name="destlist_view"),
    path('show-destinaton/<str:slug>',views.showdest_view,name="showdest_view"),
    path('update-destinaton/<str:slug>',views.updatedest_view,name="updatedest_view"),
    path('create-destinaton',views.createdest_view,name="createdest_view"),
    path('delete-destinaton/<str:slug>',views.deletedest_view,name="deletedest_view"),

    ########Site path##########
    path('sites-list',views.sitelist_view,name="sitelist_view"),
    path('show-site/<str:slug>',views.showsite_view,name="showsite_view"),
    path('update-site/<str:slug>',views.updatesite_view,name="updatesite_view"),
    path('create-site',views.createsite_view,name="createsite_view"),
    path('delete-site/<str:slug>',views.deletesite_view,name="deletesite_view"),

    ########Event path ########
    path('events-list',views.eventlist_view,name="eventlist_view"),
    path('show-event/<str:slug>',views.showevent_view,name="showevent_view"),
    path('update-event/<str:slug>',views.updateevent_view,name="updateevent_view"),
    path('create-event',views.createevent_view,name="createevent_view"),
    path('delete-event/<str:slug>',views.deleteevent_view,name="deleteevent_view"),

]

project/urls.py
from unicodedata import name
from django import views
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('admin/',admin.site.urls),
    path('destinations/',include('destination.urls',namespace="destination")),
    path('',include('home.urls',namespace="homepage")),
    path('contact-us/', include('contact.urls',namespace='contact')),
    path('',include('management.urls',namespace="management")),
    
]

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

{% load bootstrap5 %}

{% bootstrap_css %}

{% bootstrap_javascript %}

{% bootstrap_messages %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  
  <title>Discover Saudi</title>
</head>

<body>
 
  <!-- Navbar -->
  <header >
  <nav class="navbar navbar-expand-lg bg-light  py-3 fixed-top  ">
    <div class="container-fluid">
      <a href="{% url 'homepage:home_page_view' %}" class="navbar-brand text-dark">
        <img src="{% static 'logo/head_icon.svg' %}" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
        Discover Saudi Arabia</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navmenu">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a href="{% url 'homepage:home_page_view' %}" class="nav-link text-dark">Home</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'destination:destination_list_view' %}" class="nav-link text-dark">Explore</a>
          </li>

          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'logout'%}" class="nav-link text-dark">Log out</a>
            </li>
            {% if not request.user.is_superuser %} 
            <li class="nav-item">
              <a href="{% url 'accounts:profile'%}" class="nav-link text-dark">My Profile</a>
            </li>
            
          {% endif %} 
          {% else %}
          <li class="nav-item">
            <a href="{% url 'accounts:register'%}" class="nav-link text-dark">Register Now</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'login'%}" class="nav-link text-dark">Log in</a>
          </li>

          {% endif %}
          <li class="nav-item">
            <a href="{% url 'contact:contact_view'%}" class="nav-link text-dark">Contact Us</a>
          </li>

          {% if request.user.is_superuser %}
          <li class="nav-item">
            <a href="{% url 'management:destlist_view' %}" class="nav-link text-dark">All Destinations</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'management:sitelist_view' %}" class="nav-link text-dark">All Sites</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'management:eventlist_view' %}" class="nav-link text-dark">All Events</a>
          </li>
          {% endif %}
  

        </ul>
      </div>
    </div>
  </nav>
</header>



<!-- Hereeeeeeeeeeeeee -->




{% block body %}



{% endblock body %}
 
  



  
  
<footer class="py-3 my-4">
  <div class="container">
  <ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <li class="nav-item"><a href="{% url 'homepage:home_page_view' %}" class="nav-link px-2 text-muted">Home</a></li>
    <li class="nav-item"><a href="{% url 'destination:destination_list_view' %}" class="nav-link px-2 text-muted">Explore</a></li>

    <li class="nav-item"><a href="{% url 'contact:contact_view' %}" class="nav-link px-2 text-muted">Contact</a></li>
  </ul>
  <p class="text-center text-muted">&copy; 2022 Discover Saudi Arabia, Inc</p>
  <a href="#" class="position-relative bottom-0 end-0 p-5 float-end">
    <i class="bi bi-arrow-up-circle h1"></i>
  </a>
</div>

</footer>




<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>


</body>

</html>